### PR TITLE
Mint: Add `clnrest.py` Lightning backend

### PR DESCRIPTION
**Pull request by lollerfirst**
- Implements changes requested in Issue #536 
- small improvements of the checks on the same functionality in lndrest
- Ports backend for CLN to the clnrest plugin (no more dependency on external c-lightning-REST!)

### CODE REVIEW

**Comment by lollerfirst** [comment]
I merged @rbensberg branch which puts corelightningrest.py onto the newer plugin `clnrest` which comes integrated with CLN and should just work without too many hoops.

Although NOW for some reason it hangs when verifying the payment of the quote (when minting tokens). If you stop it and then check the invoice manually `cashu invoice <amount> --id <quote_id>` doesn't have any problem finding it.

**Comment by lollerfirst** [comment]
`paid_invoice_stream` was the problem. Fixed it.

**Comment by callebtc** [comment]
Thank you for the fixes in `lndrest.py`. Could you put those changes into a separate PR?

**Comment by lollerfirst** [comment]
Yea sure.

**Pull request merged**
