### PR TITLE
Add HTTP compression middleware

### PR DESCRIPTION
**Pull request by ok300**
This PR adds support for HTTP compression.

The most common algorithms are supported: `brotli`, `zstandard`, `gzip` and `deflate`, in that order. They are ordered from the newest / most efficient to older / least efficient. Which one will be used is determined by which one(s) are set in the client request's `"Accept-Encoding"` header. If no compression is set in the request, no compression will be used.

See https://github.com/cashubtc/nuts/pull/176

---

Can be tested with:

```sh
curl -H "Accept-Encoding: zstd, br, deflate, gzip" -X "GET" -I http://localhost:3338/v1/info

curl -H "Accept-Encoding: gzip" -X "GET" -I http://localhost:3338/v1/info

curl -H "Accept-Encoding: zstd" -X "GET" -I http://localhost:3338/v1/info

curl -H "Accept-Encoding: deflate" -X "GET" -I http://localhost:3338/v1/info

curl -H "Accept-Encoding: br" -X "GET" -I http://localhost:3338/v1/info
```

Compression works if the response confirms the chosen algorithm, for example if the header contains
```
﻿﻿﻿content-encoding: br
```

### CODE REVIEW

**Comment by callebtc** [comment]
Beautiful integration! Please run `make format` once to fix the import sorting issues.

**Comment by ok300** [comment]
Thanks, done!

**Review by prusnak — APPROVED** [review]
tested with Curl, Firefox, Chrome, Safari -> ACK

**Review by callebtc — APPROVED** [review]
LGTM

**Pull request merged**
